### ISSUE TITLE
Make a generic API for fetching data from Contenful

### ISSUE THREAD

**Issue by bakseter** [echo-webkom/echo.uib.no#48]
There should be one way only to fetch either events or posts from the Contentful API.
This method should have this functionality:
- Fetch n post previews with the data: title, body, author, slug and publish date. The body should be limited to 100 characters. 
- Fetch n event previews with the data: title, image, spots, location, slug and date.
- Fetch a single post by slug with all data.
- Fetch a single event by slug with all data.

**Comment by boaanes** [comment]
Implemented in branch feature/api.
Limiting body length for previews will be done in code.

**Comment by boaanes** [comment]
Change the API to return formatted types of Posts and Events
