### ISSUE TITLE
Test the generic Contentful API

### ISSUE THREAD

**Issue by bakseter** [echo-webkom/echo.uib.no#49]
There should be tests to ensure the Contentful API at #48 fetches data properly.
There should be tests for:
- Fetching n post previews with the data: title, body, author, slug and publish date. The body should be limited to 100 characters.
- Fetching n event previews with the data: title, image, spots, location, slug and date.
- Fetching a single post by slug with all data.
- Fetching a single event by slug with all data.

**Comment by alvarhonsi** [comment]
Implemented a mock api for the current api functionality to be used in future tests. Each api function has a test confirming that no data has been altered in the fetching process.
We deemed that the tests listed in the original issue were obsolete, and decided to not implement them.

**Comment by boaanes** [comment]
Test that the API returns correct types for content, see #48
