### ISSUE TITLE
Color mode bug in build

### ISSUE THREAD

**Issue by boaanes** [echo-webkom/echo.uib.no#55]
**Description**
Color mode resorts to default on each refresh, and then quickly changes to color mode stored in users local storage.

**Reproduce**
Build the website with `yarn build` then start server with `yarn start`. Change to dark color mode and refresh, watch bug in action.

**Fix**
This is a chakra-ui thing. Check the official documentation referring to color mode. The issue may lie in the order the theme is loaded.

**Comment by bakseter** [comment]
Probably a Chakra UI bug, not important for now.
